//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutodev_Assignment4_OOPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Join
    {
        public int Join_ID { get; set; }
        public Nullable<int> Player_ID { get; set; }
        public Nullable<int> Team_ID { get; set; }
        public Nullable<int> Position_ID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Position Position { get; set; }
        public virtual Team Team { get; set; }
    }
}
